TEST:
  FROM_TEMP: false
  SAVE_NAME: line_youngs
  SETTING: line

MESH:
  GRID_SIZE: 100
  RESOLUTION: 0.5
  TYPE: cartesian
  PERTURB:
    WIGGLE: 0.0
    SEED: 0
    FIX_BOUNDARY: true

GEOMS:
  FACET_ALGO: Youngs
  THRESHOLD: 1.0e-10
  DO_C0: false

ADVECTION:
  DO_ADVECT: false
